### PR TITLE
Change links to relative references

### PR DESCRIPTION
**Pull request by crclark96**
Realized my previous patch redirects links to my fork instead of within the file itself -- fixed this.

### CODE REVIEW

**Comment by michelpereira** [comment]
Hi, thanks for your help with the links but please check again C# because it's not working. I don't know the best way to handle this, if it's better to use 'c\#' or 'c#-1'.

Thanks.

**Comment by crclark96** [comment]
Resolved. The links are now also relative, so if someone makes a copy, the links will lead within their own document instead of back to this one.

**Comment by michelpereira** [comment]
I tried on your repo and the C# link is not working, I'll try to get help to fix this.

**Comment by crclark96** [comment]
Were you looking at this branch: https://github.com/crclark96/gamesofcoding/tree/patch-3 ?

My master branch isn't synced with this patch yet. It worked on patch-3 when I tested it just now.

**Comment by michelpereira** [comment]
Done, thanks for let me know about the branch.

**Pull request merged**
